name: unite
description: "Your Health, Your Way, Your Choice!"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
    # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  flutter_native_splash: ^2.3.9
  smooth_page_indicator: ^1.1.0

  # Utilities
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/images/on_boarding_images/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
          style: italic
          weight: 200
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
          style: italic
          weight: 300
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
          style: italic
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 500
          style: italic
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 600
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 800
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
          style: italic
          weight: 800
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
          style: italic
          weight: 900
